import {
  ArrowRight,
  Clock3,
  LogIn,
  MessageCircle,
  RadioTower,
  ShieldCheck
} from "lucide-react";
import { TalkNestScene } from "./components/TalkNestScene";

const features = [
  {
    icon: LogIn,
    title: "Login first",
    body: "Predefined demo users authenticate through the Node API before chat access."
  },
  {
    icon: RadioTower,
    title: "Live delivery",
    body: "Socket.io broadcasts every accepted message to connected users in the room."
  },
  {
    icon: Clock3,
    title: "Server time",
    body: "Message timestamps are generated by the backend and rendered beside each bubble."
  },
  {
    icon: ShieldCheck,
    title: "Session guard",
    body: "JWT auth protects REST routes and Socket.io connections until logout clears storage."
  }
];

export function App() {
  return (
    <>
      <header className="site-header">
        <a className="brand-link" href="#top" aria-label="TalkNest home">
          <MessageCircle aria-hidden="true" size={22} />
          <span>TalkNest</span>
        </a>
        <nav aria-label="Primary navigation">
          <a href="#features">Features</a>
          <a href="#stack">Stack</a>
          <a href="#demo">Demo</a>
        </nav>
      </header>

      <main id="top">
        <section className="hero">
          <TalkNestScene />
          <div className="hero-copy">
            <p className="eyebrow">Real-time chat MVP</p>
            <h1>TalkNest</h1>
            <p className="lede">
              A mobile-first chat product with login, live Socket.io messaging,
              readable timestamps, and a clean path for teams to expand later.
            </p>
            <div className="hero-actions" aria-label="Project actions">
              <a className="primary-action" href="#demo">
                <span>Run locally</span>
                <ArrowRight aria-hidden="true" size={19} />
              </a>
              <a className="secondary-action" href="#features">
                View features
              </a>
            </div>
          </div>
        </section>

        <section className="feature-band" id="features">
          <div className="section-heading">
            <p className="eyebrow">MVP coverage</p>
            <h2>Everything in the first chat loop</h2>
          </div>
          <div className="feature-grid">
            {features.map((feature) => (
              <article className="feature-card" key={feature.title}>
                <feature.icon aria-hidden="true" size={24} />
                <h3>{feature.title}</h3>
                <p>{feature.body}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="split-band" id="stack">
          <div>
            <p className="eyebrow">Architecture</p>
            <h2>One product, three focused runtimes</h2>
          </div>
          <div className="stack-list">
            <div>
              <strong>Expo React Native</strong>
              <span>Login, persisted session, chat UI, Socket.io client.</span>
            </div>
            <div>
              <strong>Node.js backend</strong>
              <span>Express auth, JWT sessions, SQLite storage, Socket.io room.</span>
            </div>
            <div>
              <strong>Vite landing page</strong>
              <span>Responsive marketing surface with a performant Three.js hero.</span>
            </div>
          </div>
        </section>

        <section className="demo-band" id="demo">
          <div>
            <p className="eyebrow">Local demo</p>
            <h2>Use the seeded users</h2>
            <p>
              Sign in as <code>alex</code>, <code>mira</code>, or <code>sam</code>
              with <code>password123</code>. Open two clients to see messages
              arrive instantly in both sessions.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
