import {
  ArrowRight,
  Clock3,
  LogIn,
  MessageCircle,
  PanelLeft,
  RadioTower,
  ShieldCheck,
} from "lucide-react";
import { TalkNestScene } from "./components/TalkNestScene";

const appUrl = import.meta.env.VITE_TALKNEST_APP_URL ?? "http://127.0.0.1:8081";

const features = [
  {
    icon: LogIn,
    title: "Create your handle",
    body: "New users sign up with a unique handle, then authenticate through the Node API.",
  },
  {
    icon: RadioTower,
    title: "Live delivery",
    body: "Socket.io broadcasts accepted messages to the shared room or an authorized personal thread.",
  },
  {
    icon: Clock3,
    title: "Server time",
    body: "Message timestamps are generated by the backend and rendered beside each bubble.",
  },
  {
    icon: ShieldCheck,
    title: "Session guard",
    body: "JWT auth protects REST routes, Socket.io connections, and private conversation access.",
  },
  {
    icon: PanelLeft,
    title: "Sidebar inbox",
    body: "A WhatsApp-style sidebar keeps contacts, handle search, and account status visible.",
  },
];

export function App() {
  return (
    <>
      <header className="site-header">
        <a className="brand-link" href="#top" aria-label="TalkNest home">
          <MessageCircle aria-hidden="true" size={22} />
          <span>TalkNest</span>
        </a>
        <nav aria-label="Primary navigation">
          <a href="#features">Features</a>
          <a href="#stack">Stack</a>
          <a className="nav-cta" href={appUrl}>
            Open app
          </a>
        </nav>
      </header>

      <main id="top">
        <section className="hero">
          <TalkNestScene />
          <div className="hero-copy">
            <p className="eyebrow">Real-time chat MVP</p>
            <h1>TalkNest</h1>
            <p className="lede">
              A real-time chat product with sign-up, personal handles, private
              conversations, readable timestamps, and a focused inbox layout.
            </p>
            <div className="hero-actions" aria-label="Project actions">
              <a className="primary-action" href={appUrl}>
                <span>Open TalkNest</span>
                <ArrowRight aria-hidden="true" size={19} />
              </a>
              <a className="secondary-action" href="#features">
                View features
              </a>
            </div>
          </div>
        </section>

        <section className="feature-band" id="features">
          <div className="section-heading">
            <p className="eyebrow">MVP coverage</p>
            <h2>Everything in the first chat loop</h2>
          </div>
          <div className="feature-grid">
            {features.map((feature) => (
              <article className="feature-card" key={feature.title}>
                <feature.icon aria-hidden="true" size={24} />
                <h3>{feature.title}</h3>
                <p>{feature.body}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="split-band" id="stack">
          <div>
            <p className="eyebrow">Architecture</p>
            <h2>One product, three focused runtimes</h2>
          </div>
          <div className="stack-list">
            <div>
              <strong>Expo React Native</strong>
              <span>
                Sign-up, persisted sessions, sidebar inbox, Socket.io client.
              </span>
            </div>
            <div>
              <strong>Node.js backend</strong>
              <span>
                Express auth, JWT sessions, SQLite storage, Socket.io rooms.
              </span>
            </div>
            <div>
              <strong>Vite landing page</strong>
              <span>
                Responsive entry point linked directly to the main app.
              </span>
            </div>
          </div>
        </section>

        <section className="app-band" id="app">
          <div>
            <p className="eyebrow">Main app</p>
            <h2>Start from your own handle</h2>
            <p>
              Create an account, share your handle, then open personal chats
              from the sidebar without relying on preloaded accounts.
            </p>
            <div className="app-actions">
              <a className="primary-action inverse-action" href={appUrl}>
                <span>Go to app</span>
                <ArrowRight aria-hidden="true" size={19} />
              </a>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
